### PR TITLE
request.get timeouts, process-list.sh, requirements.txt

### PR DESCRIPTION
**Pull request by sickcodes**
Add timeouts for requests, otherwise requests can hang forever.

Added process-list.sh

```bash
./process-list.sh id_list.txt
```

Added requirements.txt for pipenv, pyenv, conda QOL.

### CODE REVIEW

**Comment by cpuuntery** [comment]
your pull request is awesome. i love it

**Comment by sickcodes** [comment]
> your pull request is awesome. i love it

Thanks!

@egbertbouman any plans to merge?

**Comment by egbertbouman** [comment]
I'm not sure about supporting bulk processing like this, as it is platform-dependent.
Adding a timeout to the HTTP requests and requirements.txt does make sense, though.

**Comment by egbertbouman** [comment]
Since it seems that more people want this functionality, I guess we could add something similar to the code I posted [here](https://github.com/egbertbouman/youtube-comment-downloader/issues/52#issuecomment-676557291).
And just add this functionality to `downloader.py`.

**Comment by sickcodes** [comment]
> I'm not sure about supporting bulk processing like this, as it is platform-dependent.
> 
> Adding a timeout to the HTTP requests and requirements.txt does make sense, though.

True, it's just a script tho, maybe put in a tools folder?

requirements is pretty much standard otherwise users have to open the python file and find it anyway.

Script good for docker, VPS, Linux and Mac users.

In fact, Windows subsystem for Linux users can use it too now.

**Pull request closed without merging**
