### PR TITLE
Python Package

### PR DESCRIPTION
**Pull request by seppeljordan**
This PR adds the proper metadata files to make this a python package. It uses setuptools to achieve this.

In packaging process a entry point for a console script was created that should make the program more convenient to use for python beginners and non-techies.

If you are interested in merging this, please give some feedback since I believe there should be some more work done on this PR.

EDIT:

Making this a package would solve the issue of platform independence created by #58 since the bulk processing functionality could be moved to a separate console script that would be registered with setuptools.

### CODE REVIEW

**Comment by egbertbouman** [comment]
Cool, thanks! I'm definitely interested in merging this.

Registering an additional console script for bulk processing also sounds good :+1:

**Comment by seppeljordan** [comment]
Hey @egbertbouman ,
thanks for the quick reply.

The name for the console script is just a placeholder. If you already have an idea about the name, tell me and I'll use it in this PR. Same goes for names of modules and folders.

Cheers

**Comment by seppeljordan** [comment]
Hi @egbertbouman ,

I was wondering how we proceed with this PR?

Cheers

**Comment by egbertbouman** [comment]
The PR looks good! If you're ready, I'll merge it.

**Comment by seppeljordan** [comment]
:) Currently the package package metadata does not include version information. Should it just be 1.0?

**Comment by egbertbouman** [comment]
Maybe you can add 0.1 as the version number, although I'll probably never change it. Unless we start creating releases on PyPI.

**Comment by seppeljordan** [comment]
I think this PR is ready to be merged.

**Comment by egbertbouman** [comment]
Thanks!

**Pull request merged**
