### PR TITLE
Added Username, refactored installation

### PR DESCRIPTION
**Pull request by geekodour**
some fixes and a new important field.

### CODE REVIEW

**Comment by CygnusX01** [comment]
Guys, good evening. Thank you very much for this script. I´m a beginner and I only need this script in order to make my PhD research in Applied Linguistics. How much you guys would charge to send me a full example script in order fo to fill with my own ids and output name? Thank you very much

**Comment by d0tN3t** [comment]
@CygnusX01 Give me an example of what you're wanting to do plz.

**Comment by CygnusX01** [comment]
> @CygnusX01 Give me an example of what you're wanting to do plz.

Hello d0tN3t! I need to retrieve all comments of any given Youtube Video in order for me to manipulate the output in a .txt file. When I hvae all comments, I´m gonna run a language program called WordSmith Tools to analyse the whole content at once. This script you have here is good, but I dont know how or where to fill in with the info of the Youtube video I want to retrieve info...

**Comment by d0tN3t** [comment]
No problem, I can help you. Can you email me at jason.quintana1@gmail.com
with youtube id information plz.
I'll be more than happy to help you with this.

**Comment by egbertbouman** [comment]
Sorry that I never responded until now. Since the underlying fork was removed, I'm closing this PR.

**Pull request closed without merging**
